package:
  name: {{PKG_NAME|default("viral-ngs")}}
  version: {{PKG_VERSION_CONDA}}

about:
  home: https://github.com/broadinstitute/viral-ngs
  license: https://raw.githubusercontent.com/broadinstitute/viral-ngs/master/LICENSE
  summary: A set of scripts and tools for the analysis of viral NGS data

source:
  fn: viral-ngs-{{SRC_FILE_PREFIX}}.zip
  url: https://github.com/broadinstitute/viral-ngs/archive/{{SRC_FILE_PREFIX}}.zip

build:
    number: 0
    rpaths:
        - lib/
        - lib//

requirements:
  build:
    - {{ "{{ compiler('c') }}" }}
    # - gcc   # [not osx]
    # - llvm  # [osx]

  host:
    - python
    - openjdk >=8
    - perl
    {% for item in build_requirements %}
    {{ item }}
    {%- endfor %}
    # C lib or compilation-related

  run:
    - python
    - openjdk >=8
    - perl
    {% for item in run_requirements %}
    {{ item }}
    {%- endfor %}
    {% for item in py3_run_requirements %}
    {{ item }} # [py3k]
    {%- endfor %}
    {% for item in linux_run_requirements %}
    {{ item }} # [linux]
    {%- endfor %}
    {% for item in osx_run_requirements %}
    {{ item }} # [osx]
    {%- endfor %}
    # C lib-related
    - libgcc # [not osx]

test:
  requires:
    # testing-related
    {% for item in test_requirements %}
    {{ item }}
    {%- endfor %}
  commands:
    # test command-line tools
    - "assembly.py -h &> /dev/null"
    - "broad_utils.py -h &> /dev/null"
    - "illumina.py -h &> /dev/null"
    - "interhost.py -h &> /dev/null"
    - "intrahost.py -h &> /dev/null"
    - "metagenomics.py -h &> /dev/null"
    - "ncbi.py -h &> /dev/null"
    - "read_utils.py -h &> /dev/null"
    - "kmer_utils.py -h &> /dev/null"
    - "reports.py -h &> /dev/null"
    - "taxon_filter.py -h &> /dev/null"

    # test tool install
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_tools.py"

    # various unit tests
    #cd 
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_tools_vphaser2.py"
    - "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_tools_picard.py"
    - "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_tools_samtools.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_taxon_filter.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_util_misc.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_util_vcf.py"    
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_snake.py" # [py3k]
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_read_utils.py"
    #- "cd $(dirname $(which illumina.py))/../opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_tools_novoalign.py"

    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_interhost.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_intrahost.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_assembly.py"
    #- "cd $PREFIX/opt/$PKG_NAME-$PKG_VERSION && py.test -v test/unit/test_illumina.py"
