name: 'Setup Docker Build'
description: 'Checkout, setup buildx, and login to GHCR'
inputs:
  github-token:
    description: 'GitHub token for GHCR login'
    required: true
  checkout:
    description: 'Whether to checkout repository'
    default: 'true'
  fetch-depth:
    description: 'Git fetch depth'
    default: '1'
  fetch-tags:
    description: 'Whether to fetch tags'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
