Vagrant.configure("2") do |config|
  # This configuration is for our local box, when we use virtualbox as the provider
  config.vm.provider :virtualbox do |vb, override|
    vb.customize ["modifyvm", :id, "--memory", 4096]
    config.vm.hostname = "viral-ngs-vm"
    
    override.vm.box = "viral-ngs-vm"
    override.vm.box = "ubuntu/vivid64"

    override.vm.synced_folder ".", "/vagrant", disabled: true
    override.vm.synced_folder "./data/", "/home/vagrant/data/", create: true

    override.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible-playbook.yml"
        ansible.extra_vars = {
          user: "vagrant",
        }
    end
  end

  # This configuration is for our EC2 instance
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV["EC2_ACCESS_KEY_ID"]
    aws.secret_access_key = ENV["EC2_SECRET_ACCESS_KEY"]
    # ubuntu AMI, see: https://cloud-images.ubuntu.com/locator/ec2/
    # Vivid 15.04, amd64 hvm:ebs-ssd @ us-west-2
    aws.ami = "ami-73b4af43"
    aws.keypair_name = "tomkinsc-us-west-2"
    aws.region = "us-west-2"
    #aws.security_groups = ["sg-3a2c025f"]

    override.vm.box = "viral-ngs-vm"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "tomkinsc-us-west-2.pem"

    override.vm.synced_folder ".", "/ubuntu", disabled: true
    override.vm.synced_folder "./data/", "/home/ubuntu/data/", create: true

    override.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible-playbook.yml"
        ansible.extra_vars = {
          user: "ubuntu",
        }
    end
  end 

end