#!/bin/bash
# Call vphaser variant caller
# First argument is OMP_NUM_THREADS; remaining arguments are passed to variant_caller.

curdir=`dirname $0`

OMP_NUM_THREADS=$1 $curdir/bin/variant_caller ${*:2}
